### ISSUE TITLE
How to install it without Nuget

### ISSUE THREAD

**Issue by akeilox** [umbraco/UmbracoExamine.PDF#1]
I have a site without VS or nuget. Can you please share on how to install this on a live installation?
Thank you

**Comment by Shazwazza** [comment]
You can download the nupkg file direct from nuget : https://www.nuget.org/packages/UmbracoCms.UmbracoExamine.PDF/1.0.0

then click the Download link on the left side menu. a .nupkg file is just a zip so if you rename it to .zip then you can extract it. You'll find the DLLs in the lib folder.

You should of course test the installation on a test environment before you put it on a live environment :)

**Comment by Shazwazza** [comment]
Hi, we've added a zip download to the releases page here with some instructions as well:

https://github.com/umbraco/UmbracoExamine.PDF/releases/tag/v1.0.0
