### ISSUE TITLE
Update Readme to Recommend ExamineFileIndexer Instead

### ISSUE THREAD

**Issue by Nicholas-Westby** [umbraco/UmbracoExamine.PDF#10]
ExamineFileIndexer was just released: https://our.umbraco.org/projects/backoffice-extensions/examinefileindexer/

It appears to have the benefits of UmbracoExamine.PDF without the licensing concerns. Perhaps it would be worth updating the readme to recommend people use that package rather than this one?

**Comment by Shazwazza** [comment]
Sure, I'm sure we mention this library in a couple of places where we could probably mention both libraries. Of course Umbraco HQ cannot directly support ExamineFileIndexer but will be worth mentioning the options available. Would you be able to put together any PRs for readme + docs?

**Comment by nul800sebastiaan** [comment]
This has been open for a while now and it's still a good idea but it seems like nobody has had time to pick it up.

I'll close this for now and add the `idea` tag so we can find it later when we have some more time to spend on this.
