### ISSUE TITLE
Not getting FileTextContent when using blob storage

### ISSUE THREAD

**Issue by t9creative** [umbraco/UmbracoExamine.PDF#11]
Should this work with indexing PDFs when using azure blob storage?  If so, should it work "out of the box" or no?  I was able to get FileTextContent locally, but when switcched to azure blob storage, it wasn't indexing the file contents.

Thanks!

**Comment by Shazwazza** [comment]
I don't think this lib supports Umbraco's `IFileSystem`, it will need an update for that.

**Comment by t9creative** [comment]
Thanks @Shazwazza for following up.  Would love to be able to see this working with azure blob storage in the future!

**Comment by Sam7** [comment]
@Shazwazza Just provided a pull request to address this issue.

**Comment by DavidSigemo** [comment]
What is the status of this?

**Comment by Shazwazza** [comment]
Just released a 2.0.1 version which has this issue resolved.
