### ISSUE TITLE
UmbracoExamine.PDF Support for Umbraco v8

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoExamine.PDF#14]
Need to update the project to support v8

While we are doing this we should look at replacing iTextSharp (which requires a license) with PDFSharp (http://www.pdfsharp.net/) which is MIT licensed... if it works.

---
_This item has been added to our backlog [AB#1610](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1610)_

**Comment by cdecinkoKnight** [comment]
Also, update to support the latest v.7.

**Comment by cleversolutions** [comment]
I've built a PDF indexer in V8 using PDFSharp. It shouldn't be very much work to migrate that into this package if your interested in a pull request.

**Comment by Shazwazza** [comment]
Hi! That would be wonderful if you could send a PR :)
