### ISSUE TITLE
iTextSharp deprecated

### ISSUE THREAD

**Issue by cdecinkoKnight** [umbraco/UmbracoExamine.PDF#16]
iTextSharp is now deprecated. It is being advised to use a new version that you have to purchase.

**Comment by Shazwazza** [comment]
thanks for the info - side note, itextsharp has always been licensed for purchase, see https://github.com/umbraco/UmbracoExamine.PDF#license

There an umbraco 8 PR to replace this library https://github.com/umbraco/UmbracoExamine.PDF/pull/15 which we'll hopefully get to soon and potentially back port.

**Comment by Shazwazza** [comment]
v2.0 of this package has been made available for v8 which uses PDFSharp as the default implementation for reading PDF, it is easy to replace this implementation with something else if that doesn't suit, see release notes https://github.com/umbraco/UmbracoExamine.PDF/releases/tag/v2.0.0
