### ISSUE TITLE
Improve Text Extraction with PDFSharp

### ISSUE THREAD

**Issue by cleversolutions** [umbraco/UmbracoExamine.PDF#18]
The author of PDFSharp says it is possible to do PDF text extraction with his library using lower level APIs. So going on that assumption, it should be possible to improve the extraction we are doing with PdfSharpTextExtractor.

The current implementation of text extraction we use in UmbracoExamin.PDF doesn't make use of embedded CMAP files. As I understand it, some PDFs will represent the ASCII characters as non ASCII characters and you need to do a character substitution as per the CMAP tables. There is a blog post about CMAP tables here https://blog.idrsolutions.com/2012/05/understanding-the-pdf-file-format-embedded-cmap-tables. Also there is a closed github issue (https://github.com/empira/PDFsharp/issues/49) on PDFSharp about unicode issues that roughly indicates what needs to be done. 

I hope to have a pull request in a few days with a rewrite of PdfSharpTextExtractor that hopefully will extract text from the windows-vista.pdf test. I have a lot more work to do, so at this point I can't even validate if this concept is accurate yet, but I think it is promising.

**Comment by Shazwazza** [comment]
Sounds amazing and yes it all comes down to the implementation of the reader, there's a note in the code about this exact thing https://github.com/umbraco/UmbracoExamine.PDF/blob/master/src/UmbracoExamine.PDF/PdfSharpTextExtractor.cs#L15

**Comment by cleversolutions** [comment]
That looks exactly like what I’m working on. PDFSharp doesn’t parse the CMAPs, but it’s not too hard. Each font can have its own CMAP, to select the font I’ll process the TF operator and extract the current font then do the substitution on the current font.

**Comment by cleversolutions** [comment]
My naive first attempt at the CMAP mapping went well, the vista document looks decent, but there are a few characters here and there that didn't work. I have other test documents that are not extracting as well. I'm reading through the PDF spec right now and of course it's much more complicated than I expected. Which is all to say, that PR may be more than a few days away.
