### ISSUE TITLE
Not getting FileTextContent when using blob storage (Umbraco 7)

### ISSUE THREAD

**Issue by timeverts** [umbraco/UmbracoExamine.PDF#20]
@Shazwazza, I am migrating an existing Umbraco 7 site to Azure hosting and am using Azure Blob Storage for media. I was able to get `FileTextContent` field when indexing locally, but when I switched to Azure Blob Storage, it's no longer indexing the file contents.

I see in #11 that you added support for this, but it was only pushed out to a release that supported Umbraco 8.  Would it be possible to release a patch on the 1.x release stream, so it's supported in Umbraco 7 (>= 7.3.0) as well? 

This is a pretty big road block for the hosting migration! FYI: The client's site is running Umbraco 7.3.0.

Really hope you're able to help.

**Comment by timeverts** [comment]
@Sam7 you worked on the pull request for the Umbraco 8 fix. Do you think it is relatively easy to do the same to Umbraco 7?

**Comment by timeverts** [comment]
> @Sam7 you worked on the [pull request](https://github.com/Sam7/UmbracoExamine.PDF/commit/7c1f161a500af4ea593ce7ffc8006030fc15e6b3) for the Umbraco 8 fix. Do you think it is relatively easy to do the same to Umbraco 7?

Sorry @Sam7, I just realised your pull request _was_ actually for the Umbraco 7 compatible version of the library, but it wasn't incorporated into the 1.x release.

@Shazwazza, is there any chance you could create an Umbraco 7 compatible release based on the changes in @Sam7's pull request?

**Comment by Shazwazza** [comment]
I have pushed code to fix this to a v1 branch https://github.com/umbraco/UmbracoExamine.PDF/commit/e908b7aed309b088783a0fcebd5430e60aae0d9c

Here's a build output. Internally i don't think there's much time to have this reviewed so I've marked with the `community/review` tag. It would be much appreciated that you can do both a code review and testing for this one and then i can publish this release. The code should have no breaking changes. If you can please test with both the blob storage media provider and without that would be great!

[UmbracoCms.UmbracoExamine.PDF.1.0.3.zip](https://github.com/umbraco/UmbracoExamine.PDF/files/4506925/UmbracoCms.UmbracoExamine.PDF.1.0.3.zip)

Let me know the outcome and then i can get this published.

**Comment by timeverts** [comment]
Thanks so much @Shazwazza. I really appreciate you taking the time to put this build together, particularly because it's an old build. I will aim to get this tested this week and get back to you.

**Comment by timeverts** [comment]
@Shazwazza, I've done some quite extensive testing in Umbraco 7.3.0, testing both local file system media and blob storage media. When testing using the Umbraco back office indexing and search tools (in Examine Management), I can confirm that the `FileTextContent` field is now being returned in results for both storage types.

So I am keen for this release to be rolled out officially via Nuget. 

Thanks so much for all your work on this.

**Comment by timeverts** [comment]
@Shazwazza, any update on when you might be able to integrate this into the official nuget release channel?

**Comment by Shazwazza** [comment]
@timeverts have published now https://www.nuget.org/packages/UmbracoCms.UmbracoExamine.PDF/1.0.3
