### ISSUE TITLE
Failing to index - possible reasons?

### ISSUE THREAD

**Issue by joeriks** [umbraco/UmbracoExamine.PDF#4]
I tried the package on a site with many pdfs. But the Pdf-indexer only indexed two of them. I wonder if it might be because it had problems reading some of the pdfs and should it log an error in that case? The site log does not have any errormessage about that.

**Comment by Shazwazza** [comment]
This is all up to iTextSharp, if it actually decides to throw an error if it can't read it then this is handled:

https://github.com/umbraco/UmbracoExamine.PDF/blob/9386ba86ccc48c71e59225071f5b931e6734c02f/src/UmbracoExamine.PDF/PDFIndexer.cs#L139

And Umbraco should wire up Examine error event handlers to log. However, iTextSharp doesn't necessarily throw errors if it can't read PDFs
