### ISSUE TITLE
Rebuilding the index when there is an empty file value

### ISSUE THREAD

**Issue by EnterpriseWide** [umbraco/UmbracoExamine.PDF#8]
When I add a PDF to the Media Library, the pdf can be found using the /Developer/{Examine Management Tab}/ and searching in the PDF Searcher.
However, when I rebuild the index, all the pdf docs get removed from the index and the searcher can no longer find the pdf.
I am using Umbraco 7.3.0
There seems to be an issue with the way the Rebuild Index feature recognises pdf files.

**Comment by Shazwazza** [comment]
I have just tested this but I cannot replicate. I have released version 1.0.1, can you please update to use this and re-test? 

https://www.nuget.org/packages/UmbracoCms.UmbracoExamine.PDF/1.0.1

**Comment by EnterpriseWide** [comment]
I actually had to remove the package on the install because of the licencing and can't test it anymore. Please close this issue. I'll keep my eye for it on the next site that needs pdf indexing.

**Comment by ismailmayat** [comment]
I am also having this issue using umbraco 7.3.5 and latest version of UmbracoExamine.pdf from nuget so 1.0.1 nothing on the log really strange.  On save you get content in the index however on rebuild its all gone.

**Comment by ismailmayat** [comment]
I found that if you have blank media entry that causes re indexing to fail.  Remove it and everything works.

**Comment by Shazwazza** [comment]
Can you elaborate on what you mean by 

> blank media entry that causes re indexing to fail

**Comment by ismailmayat** [comment]
Go to media section create media item image or file but do not upload anything.  This will reproduce the issue

**Comment by Shazwazza** [comment]
cool thx, i'll try to get a new release out soon then

**Comment by BatJan** [comment]
Just to chime in I have been struggling with the same issue today - I had around 9 media items where no files where mapped. Once they were fully deleted (like gone from the recycle been too) the indexer started running - I'm just puzzled that trashed items are also being looped over? Does that make sense? :)

Anyhow now I'm seeing a lot of entries in the log saying something like 
2016-03-17 14:17:10,862 [P3584/D45/T106] ERROR UmbracoExamine.DataServices.UmbracoLogService - Provider=PDFIndexer, NodeId=20173
System.Exception: UmbracoExamine.FileIndexer: Extension '.png' is not supported at this time - Don't know if that's a seperate thing though?

**Comment by ismailmayat** [comment]
Shannon,

See https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/74773-pdfindexer-examine-rebuild-index-issue#comment-239418 has the offending line

**Comment by ismailmayat** [comment]
Jan,

I did raise something on our about that https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/74843-pdfindexer-adding-images-and-folders-to-index  its just logging that is not your issue its the blanks.

**Comment by Shazwazza** [comment]
I've just tested with this change: I have 5 media items and only 2 of them actually have files, the other ones are empty. When I rebuild, the values for the 2 PDF files are in the index.

**Comment by ismailmayat** [comment]
The empty ones are they images or files?

**Comment by BatJan** [comment]
Just did some testing and it seems to work like a charm now - Thanks a bunch for the quick release of 1.0.2 :)

**Comment by Shazwazza** [comment]
Great! @ismailmayat the tests I did were empty files, but shouldn't make a difference whether it's an image or file.

**Comment by ismailmayat** [comment]
I am on 101 ill upgrade to 102 

cheers
